# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, 16.2
# prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => :static
# end

# # Firebase configuration for New Architecture (Fabric) compatibility
# # Enable bridged/compatibility mode for Firebase with use_frameworks!
# $RNFirebaseAsStaticFramework = true
# $RNFirebaseUseFrameworks = true

# target 'naturism' do
#   rn_maps_path = '../node_modules/react-native-maps'
#   pod 'react-native-maps/Google', :path => rn_maps_path
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/..",
#     :new_arch_enabled => true,
#     :fabric_enabled => true,
#     :hermes_enabled => true
#   )

#   # Enable modular headers selectively for Firebase only
#   # This avoids conflicts with React Native runtime components
#   pod 'FirebaseCore', :modular_headers => true
#   pod 'FirebaseCoreInternal', :modular_headers => true
#   pod 'FirebaseDatabase', :modular_headers => true
#   pod 'FirebaseStorage', :modular_headers => true
#   pod 'FirebaseAnalytics', :modular_headers => true
#   # Dependencies required by FirebaseDatabase and FirebaseStorage
#   pod 'leveldb-library', :modular_headers => true
#   pod 'FirebaseAppCheckInterop', :modular_headers => true
#   pod 'FirebaseAuthInterop', :modular_headers => true
#   # Other Firebase dependencies
#   pod 'GoogleUtilities', :modular_headers => true
#   pod 'PromisesObjC', :modular_headers => true
#   pod 'nanopb', :modular_headers => true
  
#   # Disable modular headers for libwebp (causes issues)
#   pod 'libwebp', :modular_headers => false

#   post_install do |installer|
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )
#     # Avoid `mobile/ios/Pods/Headers/Public/RCT-Folly/folly/Expected.h:1587:10:
#     # 'folly/coro/Coroutine.h' file not found"`
#     #
#     # This flag is copied from the the project.pbxproj for the main project, but
#     # we also need it for the Pods project since Expo imports Folly too.
#     installer.pods_project.build_configurations.each do |config|
#       config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(OTHER_CFLAGS)']
#       config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DFOLLY_CFG_NO_COROUTINES=1'
#     end
    
#     # Configure pods for New Architecture (Fabric) with use_frameworks!
#     installer.pods_project.targets.each do |target|
#       # React Native pods configuration
#       if target.name.start_with?('React') || target.name.start_with?('RCT') || target.name.start_with?('Yoga')
#         target.build_configurations.each do |config|
#           config.build_settings['DEFINES_MODULE'] = 'NO'
#         end
#       end
      
#       # Firebase pods configuration for New Architecture compatibility
#       if target.name.include?('Firebase') || target.name.include?('GoogleUtilities') || target.name == 'leveldb-library'
#         target.build_configurations.each do |config|
#           config.build_settings['DEFINES_MODULE'] = 'YES'
#           # Ensure proper module map generation for Swift/Objective-C interop
#           config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
#           config.build_settings['CLANG_MODULES_AUTOLINK'] = 'YES'
#           # Enable Swift/Objective-C interop (required for Firebase Swift pods)
#           config.build_settings['SWIFT_OBJC_INTEROP_MODE'] = 'objc'
          
#           # For Swift pods (like FirebaseStorage), ensure Swift headers are generated
#           if target.name == 'FirebaseStorage' || target.name.include?('Firebase')
#             config.build_settings['SWIFT_VERSION'] = '5.0'
#             config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = ''
#             # Ensure Swift header is generated and accessible
#             config.build_settings['SWIFT_OBJC_INTERFACE_HEADER_NAME'] = "#{target.name}-Swift.h"
#           end
#         end
#       end
      
#       # React Native Firebase pods - ensure proper configuration
#       if target.name.include?('RNFB') || target.name.include?('react-native-firebase')
#         target.build_configurations.each do |config|
#           config.build_settings['DEFINES_MODULE'] = 'YES'
#           config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
          
#           # Add header search paths to find Firebase Swift headers
#           config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
#           # Search for Firebase Swift headers in build directory
#           config.build_settings['HEADER_SEARCH_PATHS'] << '$(PODS_CONFIGURATION_BUILD_DIR)/FirebaseStorage/FirebaseStorage.framework/Headers'
#           config.build_settings['HEADER_SEARCH_PATHS'] << '$(BUILT_PRODUCTS_DIR)/FirebaseStorage'
#           # Allow non-modular includes in framework modules (for Swift headers)
#           config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
#         end
#       end
      
#       # Ensure FirebaseStorage Swift header is generated
#       if target.name == 'FirebaseStorage'
#         target.build_configurations.each do |config|
#           # Force Swift header generation
#           config.build_settings['SWIFT_OBJC_INTERFACE_HEADER_NAME'] = 'FirebaseStorage-Swift.h'
#           config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = ''
#           # Ensure the header is public
#           config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'YES'
#         end
#       end
#     end
#   end
# end

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
#flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'naturism' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps/Google', :path => rn_maps_path
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  $RNGoogleMobileAdsAsStaticFramework = true
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  $FirebaseSDKVersion = '12.8.0'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => true
    )
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["GCC_WARN_INHIBIT_ALL_WARNINGS"] = "YES"
      end
    end
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["CC"] = "clang"
        config.build_settings["LD"] = "clang"
        config.build_settings["CXX"] = "clang++"
        config.build_settings["LDPLUSPLUS"] = "clang++"
      end
    end
    
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
          config.build_settings['EXCLUDED_ARCHS'] = 'i386'
        end
      end
      aggregate_target.user_project.save
    end
  end
end